### ISSUE TITLE
Date format not being picked up

### ISSUE THREAD

**Issue by burhan85** [catamphetamine/read-excel-file#89]
I am trying to parse an excel sheet with schema option and have specified a rule for a property as
`'Suggested Financing Period': {
        prop: 'SuggestedPeriod',
        type: Date,
        dateFormat: "DD/MM/YYYY",
        required: true
    }`
but this property is not being handled as per the specified date format. Instead, the value is being treated as an invalid date value because it's still being picked up in "MM/DD/YYYY" format.

**Comment by catamphetamine** [comment]
I've corrected the readme:


```js
readXlsxFile(file, { dateFormat: 'MM/DD/YY' })
```

**Comment by burhan85** [comment]
I tried this but it's still not working.

**Comment by catamphetamine** [comment]
The test case seems to work.
https://github.com/catamphetamine/read-excel-file/blob/8fbcf33c4c5e850c471498303ea2b49cfeb9a73a/test/1904.test.js#L5-L7

You can investigate the issue yourself then.

**Comment by ChamaraWP** [comment]
this issue is still there. I can't set dateFormat. seems like `ParseWithSchemaOptions` type doesn't contain `dateFormat` prop
